name: Cleanup

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.PAT }}
          container: docker-python-scripts
          dry-run: false
          untagged: true
