name: Cleanup

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PAT }}
          container: michelson-interpreter-python-container
          dry-run: false
          prune-untagged: true
